### ISSUE TITLE
Dear author, Hello!When will the code be released？

### ISSUE THREAD

**Issue by Suelence-hu** [cuge1995/Mesh-Attack#1]
Dear author, Hello!
After reading your paper “3D Adversarial Attacks Beyond Point Cloud” , I appreciate your paper very much. I am eager to understand the paper more deeply by combining the source code of this paper. If you can provide  me a corresponding source code conveniently, I will be very grateful!

**Comment by cuge1995** [comment]
Thanks for your interest!
We have released the code.
