### ISSUE TITLE
Dear author, the link of the Mesh data is broken, could you please update it?

### ISSUE THREAD

**Issue by iDTer** [cuge1995/Mesh-Attack#2]
https://cloud.tsinghua.edu.cn/f/2a292c598af94265a0b8/
![image](https://user-images.githubusercontent.com/30014931/222317935-ff82ed63-9e5b-4160-a55d-72721ee91d2e.png)

**Comment by cuge1995** [comment]
Thank you for bringing this to our attention. We have corrected it.

**Comment by chenhengwei1999** [comment]
> Thank you for bringing this to our attention. We have corrected it.

Hi, author, your dataset link is broken again..., could your repair it? Many thanks.
